/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  tutorialSidebar: [
    "installation",
    "intro",
    {
      type: "category",
      label: "Concepts",
      link: {
        type: "generated-index",
        description: "Learn about the different parts of the Openlizz system.",
      },
      items: [
        "concepts/multi_tenancy",
        "concepts/applications",
        "concepts/values",
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        description:
          "Guides to discover the different commands of Lizz and how works the Openlizz system.",
      },
      items: [
        "guides/cluster",
        "guides/init",
        "guides/add",
        "guides/remove",
        "guides/refresh",
        "guides/create",
      ],
    },
    {
      type: "category",
      label: "Lizz CLI",
      link: {
        type: "generated-index",
        description: "The Lizz Command-Line Interface documentation.",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "lizz-cli",
        },
      ],
    },
  ],
  tutorials: [
    {
      type: "autogenerated",
      dirName: "tutorials",
    },
  ],
};

module.exports = sidebars;

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

module.exports = sidebars;
